### ISSUE TITLE
MSVCP100D.dll was not found

### ISSUE THREAD

**Issue by Mulsiphix** [tiagoaf5/Gounki-3D#1]
OS: Windows 10 (latest updates as of 10-05-2018)

1. Ran prolog.exe
2. Ran CGFexample.exe

System Error message box immediately pops up for one missing DLL. When I click OK, a second system error message box pops up. I've attached images of both.

![msvcp100d dll_system_error](https://user-images.githubusercontent.com/43887947/46546062-b2c50380-c88d-11e8-961b-1ad711e68252.png)
![msvcr100d dll_system_error](https://user-images.githubusercontent.com/43887947/46546063-b2c50380-c88d-11e8-87b8-1175e83fba99.png)

**Comment by tiagoaf5** [comment]
This was built and compiled in Windows 7. I suggest that you open the project with visual studio and compile it again.

After googling a bit it seems that you might be missing Microsoft Visual C++ 2012 or similar.

**Comment by Mulsiphix** [comment]
Is it possible for you to include those two DLL files in your project here on github? I found an article online about how to get the DLL files for myself, but it involves installing a ton of other files just to gain access to these two. It also requires extra work and time. If you wanted your project to be easily accessible to others, this is something you could address to achieve that end. For reference, here is the article I found:

https://social.technet.microsoft.com/Forums/windows/en-US/edccdcf8-87c9-4ae4-b5ae-6bb50ea1fe90/missing-msvcp100dll-and-msvcr100dll?forum=win10itproapps

**UPDATE**
It is worth noting that I have found three articles like this, all from Microsoft. They have me download these executables (so I cannot search for the DLL I need from within them) but they never fix the problem. I've searched for the DLL files on my system after installation, but they aren't there. Frankly, I'm confused at this point about how to obtain them. If this is happening to me, it might be happening to others =\

**Comment by Mulsiphix** [comment]
### Fixing The msvcp100d.dll and msvcr100d.dll Errors
There is an article on the Microsoft support forum that tells you how to fix this error. That article can be found here:

Missing MSVCP100.dll and MSVCR100.dll
[https://social.technet.microsoft.com/Forums/windows/en-US/edccdcf8-87c9-4ae4-b5ae-6bb50ea1fe90/missing-msvcp100dll-and-msvcr100dll?forum=win10itproapps](https://social.technet.microsoft.com/Forums/windows/en-US/edccdcf8-87c9-4ae4-b5ae-6bb50ea1fe90/missing-msvcp100dll-and-msvcr100dll?forum=win10itproapps)


**What The Article Recommends**

> **MSVCR100.DLL missing**
> Note: Install both x86 and x64 for a 64-bit OS
> 
> Microsoft Visual C++ 2010 SP1 Redistributable Package (x86)
> http://www.microsoft.com/en-us/download/details.aspx?id=8328
> 
> Microsoft Visual C++ 2010 SP1 Redistributable Package (x64)
> http://www.microsoft.com/en-us/download/details.aspx?id=13523

____________________________________________________________

> **MSVCR110.DLL missing**
> 
> Visual C++ Redistributable for Visual Studio 2012 Update 4
> http://www.microsoft.com/en-us/download/details.aspx?id=30679

____________________________________________________________

If this approach works then the 32-bit DLL file versions can be located in _Windows\System32\_ and the 64-bit version inside _Windows\SysWOW64\_ directories.

**Or You Can Download The DLLs Directly**
In the case that you wish to download the DLL files directly, it is not recommended that you add them to the system directories mentioned above. If the DLL files have been tampered with, they could cause a lot of damage if you put them in your system directories. However, it is perfectly safe to download them and place them directly into the Gounki 3D directory.

Download these DLL files and place them into the _Gounki-3D-master\LAIG3_T1_G07\bin\_

> MSVCR100.DLL
> [https://www.dllme.com/dll/files/msvcr100d_dll.html](https://www.dllme.com/dll/files/msvcr100d_dll.html)
> 
> MSVCR110.DLL
> [https://www.dllme.com/dll/files/msvcp100d_dll.html](https://www.dllme.com/dll/files/msvcp100d_dll.html)
>
